### ISSUE TITLE
Add eslint-plugin-mocha

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/eslint-plugin-fxa#6]
I've accidentally committed code that had a `it.only()` line in it, which means if accidentally merged, only 1 test in our suite would be running. Bad. It shouldn't be that easy. Well, there's a plugin, and its README points out this exact rule, so I'm probably not the only one bitten by it before.

There may be other rules in the plugin that are also useful.

https://github.com/lo1tuma/eslint-plugin-mocha

**Comment by morrme** [comment]
Can I help with this one @seanmonstar  ?

**Comment by seanmonstar** [comment]
Of course!

**Comment by morrme** [comment]
@seanmonstar Thanks!  I may need a little support to ensure I target the right files, etc.

**Comment by morrme** [comment]
@seanmonstar @vladikoff i'm guessing the plugin reference needs to go into [default.js](https://github.com/mozilla/eslint-plugin-fxa/blob/master/lib/configs/default.js) , right?

**Comment by seanmonstar** [comment]
Probably, though I haven't yet read in eslint plugin docs exactly how to include other plugins.

**Comment by pdehaan** [comment]
Not sure if embedded plugins is supported by ESLint, or if the upstream library needs to install all nested dependencies separately.

Ref: https://github.com/eslint/eslint/issues/3458
See https://github.com/feross/eslint-config-standard#usage

**Comment by morrme** [comment]
@pdehaan in testing the way it's used between components here, it seems to work fine.

**Comment by vladikoff** [comment]
Let's reopen this if we still need it
